/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adegai;

import java.awt.Cursor;

/**
 *
 * @author Joao
 */
public class NovaVendaADM extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public NovaVendaADM() {
        initComponents();
        
        botaoVoltar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        botaoFinalizar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        descricaoUser = new javax.swing.JLabel();
        caixaClientes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        caixaMeio = new javax.swing.JLabel();
        menuLateral = new javax.swing.JLabel();
        menuCima = new javax.swing.JLabel();
        botaoFinalizar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/HomeADM/logo.png"))); // NOI18N
        jPanel1.add(logoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/HomeADM/userIcon.png"))); // NOI18N
        jPanel1.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 26, -1, -1));

        user.setFont(new java.awt.Font("Jost", 1, 24)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("User");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        descricaoUser.setFont(new java.awt.Font("Jost", 2, 12)); // NOI18N
        descricaoUser.setForeground(new java.awt.Color(255, 255, 255));
        descricaoUser.setText("administrador");
        jPanel1.add(descricaoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        caixaClientes.setBackground(new java.awt.Color(255, 255, 255));
        caixaClientes.setFont(new java.awt.Font("Jost", 1, 14)); // NOI18N
        caixaClientes.setForeground(new java.awt.Color(0, 0, 0));
        caixaClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alberto", "Junior", "Carlos | *CNPJ*" }));
        caixaClientes.setBorder(null);
        caixaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaClientesActionPerformed(evt);
            }
        });
        jPanel1.add(caixaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 233, 414, 24));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jList1.setBorder(null);
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 760, -1));

        caixaMeio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/NovaVendaADM/caixaMeio.png"))); // NOI18N
        jPanel1.add(caixaMeio, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 105, 1035, -1));

        menuLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/HomeADM/menuLateral.png"))); // NOI18N
        jPanel1.add(menuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 115));

        menuCima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/HomeADM/menuCima.png"))); // NOI18N
        jPanel1.add(menuCima, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        botaoFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/NovaVendaADM/finalizar.png"))); // NOI18N
        botaoFinalizar.setBorder(null);
        botaoFinalizar.setBorderPainted(false);
        botaoFinalizar.setContentAreaFilled(false);
        botaoFinalizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/NovaVendaADM/finalizar.png"))); // NOI18N
        botaoFinalizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/NovaVendaADM/finalizarPressed.png"))); // NOI18N
        jPanel1.add(botaoFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 641, -1, -1));

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/NovaVendaADM/voltar.png"))); // NOI18N
        botaoVoltar.setBorder(null);
        botaoVoltar.setBorderPainted(false);
        botaoVoltar.setContentAreaFilled(false);
        botaoVoltar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/NovaVendaADM/voltar.png"))); // NOI18N
        botaoVoltar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/NovaVendaADM/voltarPressed.png"))); // NOI18N
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 641, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        
        new VendasADM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void caixaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaVendaADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> caixaClientes;
    private javax.swing.JLabel caixaMeio;
    private javax.swing.JLabel descricaoUser;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel menuCima;
    private javax.swing.JLabel menuLateral;
    private javax.swing.JLabel user;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
