/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adegai;

import java.awt.Cursor;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        
        gitIcon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        botaoEntrar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
    //metodo para verificar o login
    private boolean verificarLogin(boolean vLogin){
        
        String loginUser = login.getText();
        
        return loginUser.matches("joao");
    }
    
    //metodo para verificar a senha
    private boolean verificarSenha(boolean vSenha){
        
        char getPassword[] = password.getPassword();
        String correctPass = "123";
        char[] cp = correctPass.toCharArray();
        
        return Arrays.equals(getPassword, cp); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        formaLinha = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        formaLogin = new javax.swing.JLabel();
        passwordIcon = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        formaSenha = new javax.swing.JLabel();
        botaoEntrar = new javax.swing.JButton();
        gitIcon = new javax.swing.JLabel();
        formaAmarela = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/logo.png"))); // NOI18N
        jPanelLogin.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 100, -1, -1));

        formaLinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/formaLinha.png"))); // NOI18N
        jPanelLogin.add(formaLinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 350, -1, -1));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/userIcon.png"))); // NOI18N
        jPanelLogin.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 378, -1, -1));

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Jost", 0, 16)); // NOI18N
        login.setForeground(new java.awt.Color(0, 0, 0));
        login.setText("Login");
        login.setBorder(null);
        jPanelLogin.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 378, 220, -1));

        formaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/formaTexto.png"))); // NOI18N
        jPanelLogin.add(formaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/passwordIcon.png"))); // NOI18N
        jPanelLogin.add(passwordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 433, -1, -1));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Jost", 0, 16)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setText("password");
        password.setBorder(null);
        jPanelLogin.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 433, 220, -1));

        formaSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/formaTexto.png"))); // NOI18N
        jPanelLogin.add(formaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 425, -1, -1));

        botaoEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/botaoEntrar.png"))); // NOI18N
        botaoEntrar.setBorder(null);
        botaoEntrar.setBorderPainted(false);
        botaoEntrar.setContentAreaFilled(false);
        botaoEntrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/botaoEntrarPressed.png"))); // NOI18N
        botaoEntrar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/botaoEntrarPressed.png"))); // NOI18N
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        jPanelLogin.add(botaoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, -1));

        gitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/githubLogo.png"))); // NOI18N
        gitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gitIconMouseClicked(evt);
            }
        });
        jPanelLogin.add(gitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 580, -1, -1));

        formaAmarela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/formaAmarela.png"))); // NOI18N
        jPanelLogin.add(formaAmarela, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 70, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adegai/Login/bg.png"))); // NOI18N
        jPanelLogin.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //ação do botao entrar (verificando senha e login corretos
    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        
        if (verificarSenha(rootPaneCheckingEnabled) && verificarLogin(rootPaneCheckingEnabled)) {
            
            new HomeADM().setVisible(true);
            
        } else {JOptionPane.showMessageDialog(null, "Usuário ou senha inválido!!!");}
    }//GEN-LAST:event_botaoEntrarActionPerformed
    
    //ação do click no gitIcon direto ao site do projeto no github
    private void gitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gitIconMouseClicked
        
        try {
            String projectUrl = "https://github.com/jpcaparroz/adegaI";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(projectUrl));
            
        } catch (IOException e2) {}
    }//GEN-LAST:event_gitIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JLabel formaAmarela;
    private javax.swing.JLabel formaLinha;
    private javax.swing.JLabel formaLogin;
    private javax.swing.JLabel formaSenha;
    private javax.swing.JLabel gitIcon;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JTextField login;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
